 version: 2.1
 jobs: # we have TWO jobs
   test: # second job
     docker: # it runs inside a docker image, the same as above.
       - image: circleci/node:12.18.3

     steps:
       - checkout
       - run: npm install
       - run: npm test

 # Under the workflows: map, we can coordinate our two jobs, defined above.
 workflows:
   version: 2.1
   test: # this is the name of our workflow
     jobs: # and here we list the jobs we are going to run.
       - test